# Generated by Django 5.1 on 2024-09-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=256, unique=True)),
                ("full_name", models.CharField(max_length=256)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("national_code", models.CharField(max_length=10, unique=True)),
                ("birthday_date", models.DateField()),
                ("ceremony_datetime", models.DateTimeField()),
                ("country", models.CharField(default="Iran", max_length=100)),
            ],
        ),
    ]
